/**
 * Copies the ABIs the dashboard needs out of the Hardhat artifacts, so the
 * frontend never imports build output directly.
 *
 *   npx hardhat run scripts/export-abis.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const CONTRACTS = [
  'GhostLedgerModule',
  'ConfidentialTreasuryLog',
  'ConfidentialTreasuryToken',
  'TreasuryUSD',
] as const;

const ARTIFACTS = 'artifacts/contracts';
const CANDIDATES: Record<string, string> = {
  GhostLedgerModule: 'GhostLedgerModule.sol',
  ConfidentialTreasuryLog: 'ConfidentialTreasuryLog.sol',
  ConfidentialTreasuryToken: 'ConfidentialTreasuryToken.sol',
  TreasuryUSD: 'demo/TreasuryUSD.sol',
};

const lines = [
  '// Generated by scripts/export-abis.ts. Do not edit by hand.',
  '',
];

for (const name of CONTRACTS) {
  const path = join(ARTIFACTS, CANDIDATES[name], `${name}.json`);
  const { abi } = JSON.parse(readFileSync(path, 'utf8'));
  lines.push(`export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`, '');
}

mkdirSync('frontend/src/lib', { recursive: true });
writeFileSync('frontend/src/lib/abis.ts', lines.join('\n'));

console.log(`exported ${CONTRACTS.length} ABIs to frontend/src/lib/abis.ts`);
